# Generated by Django 4.0 on 2021-12-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateFinder', '0002_alter_title_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
