# Generated by Django 4.0 on 2021-12-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateFinder', '0003_alter_candidate_name_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
